#' Ask ChatGPT
#'
#' @param question The question to ask ChatGPT.
#'
#' @examples
#' \dontrun{
#' cat(ask_chatgpt("What do you think about R language?"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
ask_chatgpt <- function(question,context=NULL) {
  parse_response(gpt_get_completions(question,context))
}

#' Teach ChatGPT
#'
#' @param question Teach ChatGPT, given JSON data
#' @param file JSON data
#'
#' @examples
#' \dontrun{
#' cat(ask_chatgpt("What do you think about R language?"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
teach_chatgpt <- function(question,file=NULL) {
  if(is.null(file)) {
    parse_response(gpt_get_completions(question))
  } else {
    parse_response(gpt_get_completions(question,conversation_file = file))
  }
}
