#' Ask ChatGPT
#'
#' @param question The question to ask ChatGPT.
#'
#' @examples
#' \dontrun{
#' cat(ask_chatgpt("What do you think about R language?"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
ask_chatgpt <- function(question,knowledge_dir=NULL,context=NULL,history_file=NULL,update=TRUE) {
  #
  if(is.null(history_file)) {
    mssg_previous=NULL
  } else {
    if(!file.exists(history_file)) {
      file_path=history_file
      file_con=file(file_path,'w',encoding='utf-8')
      writeLines("[\n\n]",file_con)
      close(file_con)
    }
    mssg_previous=c(fromJSON(history_file,simplifyDataFrame = FALSE))
  }
  #
  if(is.null(knowledge_dir)) {
    mssg_knowledge=NULL
  } else {
    mssg_knowledge=learn_knoweldge(knowledge_dir)
  }
  #
  if(is.null(context)) {
    mssg_context=NULL
  } else {
    mssg_context=list(list(role="system",content=context))
  }
  result=parse_response(gpt_get_completions(
    question,
    context=mssg_context,
    conversation=append_lists(mssg_knowledge,mssg_previous)))
  if(update & !is.null(history_file)) {
    mssg_added1=list(list(role="user",content=question))
    mssg_added2=list(list(role="assistant",content=result))
    mssg_updated=append_lists(mssg_previous,mssg_added1,mssg_added2)
    file_path=history_file
    file_con=file(file_path,'w',encoding='utf-8')
    writeLines(toJSON(mssg_updated,auto_unbox = TRUE),file_con)
    close(file_con)
    #write(toJSON(mssg_updated,auto_unbox = TRUE),file=history_file)
  }
  result
}


teach_chatgpt <- function(question,context=NULL,file=NULL) {
  if(is.null(file)) {
    parse_response(gpt_get_completions(question,context))
  } else {
    parse_response(gpt_get_completions(question,context,conversation_file = file))
  }
}
